import assert from 'node:assert/strict';
import { mkdir, mkdtemp, writeFile, readFile, readdir } from 'node:fs/promises';
import { resolve, join } from 'node:path';
import { pathToFileURL } from 'node:url';
import puppeteer from 'puppeteer-core';
import { unzipSync, strFromU8 } from 'fflate';
import { renderReview } from '../src/review.js';
import { exampleDocument, exampleReview } from '../test/review-fixtures.js';

await mkdir('data', { recursive: true });
const directory = await mkdtemp(resolve('data/reader-check-'));
const downloadDir = join(directory, 'downloads');
await mkdir(downloadDir);
const document = { ...exampleDocument, filename: 'Study habits and learning outcomes.docx', warnings: ['Equations may not survive extraction. Check the original manuscript.'] };
const review = { ...exampleReview, summary: '## General impression\n\nThis synthetic manuscript explores how study habits relate to learning outcomes. The research question is clear, but self-selection and the interpretation of uncertainty need attention.\n\n## Strengths\n\nThe methods describe the recruitment setting, and the discussion identifies practical implications.\n\n## Key issues\n\nClarify the group assignment and distinguish a nonsignificant difference from evidence of equivalence [1, 2]. Narrow the population claim [3].', limitations: ['Synthetic manuscript for testing the review reader.'], comments: [...exampleReview.comments] };
for (let section = 1; section <= 12; section++) {
  document.html += `<h2>Additional analysis ${section}</h2>`;
  for (let paragraph = 1; paragraph <= 4; paragraph++) document.html += `<p>In analysis ${section}, paragraph ${paragraph}, participants reported their study preferences before the assessment. The groups were compared using the same outcome measure. Individual differences in prior experience may affect the interpretation of the observed results.</p>`;
  document.markdown += `\n\n## Additional analysis ${section}\n\nParticipants reported their study preferences before the assessment.`;
  review.comments.push({ text_snippet: `In analysis ${section}, paragraph 2, participants reported their study preferences before the assessment.`, content: `For analysis ${section}, describe how prior experience was measured and whether it was included in the comparison.\n\n- Report the group estimates and uncertainty.\n- Explain the implications for the interpretation.`, severity: section % 2 ? 'suggestion' : 'minor', reviewer: 'Editorial Reviewer' });
}
review.comments.push({ text_snippet: 'The difference was not statistically significant (p = 0.12). We therefore conclude that the two methods are equivalent.', content: 'This overlaps the equivalence comment and should select all fragments of this passage.', severity: 'major', reviewer: 'Technical Reviewer' });
document.html += '<h2>Repeated statements</h2><p>The analysis was exploratory.</p><p>The analysis was <strong>exploratory.</strong></p>';
review.comments.push({ text_snippet: 'The analysis was exploratory.', occurrence: 2, content: 'This must anchor to the second occurrence, across formatting.', severity: 'minor', reviewer: 'Technical Reviewer' });
const asset = { id: 'image-1', mimeType: 'image/png', data: 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a1ioAAAAASUVORK5CYII=' };
document.assets = [asset]; document.html += `<p><img src="data:image/png;base64,${asset.data}" alt="image-1"></p>`; document.markdown += '\n\n[Figure: image-1]';
document.html += '<table><tr>' + Array.from({ length: 15 }, (_, i) => `<th>Outcome ${i + 1}</th>`).join('') + '</tr><tr>' + '<td>12.5</td>'.repeat(15) + '</tr></table>';
const rendered = renderReview(document, review);
assert.deepEqual(rendered.invalid, []);
const artifact = join(directory, 'review.html'); await writeFile(artifact, rendered.html);
const browser = await puppeteer.launch({ executablePath: process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true, args: ['--no-sandbox'] });
try {
  const page = await browser.newPage();
  await page.emulateMediaFeatures([{ name: 'prefers-reduced-motion', value: 'reduce' }]);
  const errors = [], network = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  page.on('request', request => { if (/^https?:/.test(request.url())) network.push(request.url()); });
  const cdp = await page.createCDPSession();
  await cdp.send('Browser.setDownloadBehavior', { behavior: 'allow', downloadPath: downloadDir });
  await page.setViewport({ width: 1440, height: 1050 });
  await page.goto(pathToFileURL(artifact).href, { waitUntil: 'load' });
  await page.waitForSelector('html.enhanced');
  await page.evaluate(() => document.fonts.ready);
  assert.equal(await page.evaluate(() => document.fonts.check('400 16px "Instrument Sans"')), true);
  assert.equal(await page.evaluate(async () => (await document.fonts.load('italic 400 16px "Instrument Sans"')).length > 0), true);
  assert.match(await page.$eval('.paper', el => getComputedStyle(el).fontFamily), /Instrument Sans/);
  assert.equal(await page.$$eval('button', nodes => nodes.every(el => getComputedStyle(el).fontFamily.includes('Instrument Sans'))), true);
  assert.equal(await page.$$('.comment input, textarea, #comment-search, #status-filter, #notes-file').then(nodes => nodes.length), 0);
  assert.equal(await page.$$('.comment-tools, [data-passage]').then(nodes => nodes.length), 0);
  assert.equal(await page.$$eval('[data-filter-option]', nodes => nodes.every(node => node.checked)), true);
  assert.equal(await page.$eval('.review-title', el => el.textContent), 'mim-review');
  assert.equal(await page.$eval('#toolbar', el => el.offsetHeight < 80), true);
  assert.equal(await page.$$eval('.menu > summary', nodes => nodes.every(el => {
    const icon = el.querySelector('.chevron').getBoundingClientRect(), label = el.getBoundingClientRect();
    return Math.abs((icon.top + icon.bottom - label.top - label.bottom) / 2) < 3;
  })), true);
  const setPriorities = async values => {
    if (!await page.$eval('[data-filter="priority"]', el => el.open)) await page.click('[data-filter="priority"] > summary');
    await page.click('[data-filter="priority"] [data-filter-action="none"]');
    for (const value of values) await page.click('[data-filter-option="priority"][value="' + value + '"]');
  };
  await page.screenshot({ path: join(directory, 'desktop.png') });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.click('#anchor-1');
  await page.waitForSelector('#comment-1.is-active');
  await page.waitForFunction(() => Math.abs(document.querySelector('#comment-1').getBoundingClientRect().top - document.querySelector('mark[data-comments~="comment-1"]').getBoundingClientRect().top) < 3);
  await page.screenshot({ path: join(directory, 'desktop-active.png') });
  assert.equal(await page.evaluate(() => {
    const heading = document.getElementById('comments-heading').getBoundingClientRect();
    const toolbar = document.getElementById('toolbar').getBoundingClientRect();
    return Math.abs(heading.top - toolbar.bottom) < 2 && document.getElementById('comment-1').getBoundingClientRect().top > heading.bottom;
  }), true);
  await page.click('[data-action="next"]');
  await page.waitForSelector('#comment-16.is-active');
  await page.click('[data-action="previous"]');
  await page.waitForSelector('#comment-1.is-active');
  await setPriorities([]);
  assert.equal(await page.$$eval('.comment:not([hidden])', nodes => nodes.length), 0);
  assert.equal(await page.$eval('[data-filter="priority"] .filter-label', el => el.textContent), 'No priorities');
  await page.click('[data-filter="priority"] [data-filter-action="all"]');
  assert.equal(await page.$$eval('.comment:not([hidden])', nodes => nodes.length), 17);
  await setPriorities(['suggestion', 'minor']);
  assert.equal(await page.$$eval('.comment:not([hidden])', nodes => nodes.length), 14);
  await page.screenshot({ path: join(directory, 'priority-filter.png') });
  await setPriorities(['suggestion']);
  assert.equal(await page.$('#comment-1.is-active'), null);
  assert.ok(await page.$eval('#comment-1', el => el.hidden));
  await page.evaluate(() => { location.hash = '#comment-2'; });
  await page.waitForSelector('#comment-2.is-active');
  assert.equal(await page.$$eval('[data-filter-option="priority"]', nodes => nodes.every(node => node.checked)), true);
  await page.click('[data-filter="priority"] > summary');
  await page.click('mark[data-comments="comment-2 comment-16"]');
  await page.waitForSelector('#overlap-picker:not([hidden])');
  assert.equal(await page.$$eval('#overlap-picker button', buttons => buttons.length), 2);
  await page.click('#overlap-picker button:last-child');
  await page.waitForSelector('#comment-16.is-active');
  assert.ok(await page.$$eval('.paper mark.active', nodes => nodes.length) >= 2);
  await page.evaluate(() => { location.hash = '#comment-1'; });
  await page.waitForSelector('#comment-1.is-active');
  const getDownload = async (kind, extension) => {
    const before = new Set(await readdir(downloadDir));
    await page.click('#download-menu > summary');
    await page.click(`[data-download="${kind}"]`);
    for (let i = 0; i < 100; i++) {
      const found = (await readdir(downloadDir)).find(name => !before.has(name) && name.endsWith(extension));
      if (found) return join(downloadDir, found);
      await new Promise(resolve => setTimeout(resolve, 50));
    }
    throw new Error('Download did not complete: ' + kind);
  };
  const reportFile = await getDownload('report', '.md');
  assert.match(await readFile(reportFile, 'utf8'), /Scope and limitations/);
  await setPriorities(['major']);
  const fullFile = await getDownload('full', '.zip');
  const fullFiles = unzipSync(new Uint8Array(await readFile(fullFile)));
  assert.match(strFromU8(fullFiles['review.md']), /figures\/image-1.png/);
  assert.deepEqual(Buffer.from(fullFiles['figures/image-1.png']), Buffer.from(asset.data, 'base64'));
  const htmlFile = await getDownload('html', '.html');
  const exportedHtml = await readFile(htmlFile, 'utf8');
  assert.doesNotMatch(exportedHtml, /class="enhanced"/);
  await page.goto(pathToFileURL(htmlFile).href, { waitUntil: 'load' });
  await page.waitForSelector('html.enhanced');
  assert.equal(await page.$$eval('[data-filter-option]', nodes => nodes.every(node => node.checked)), true);
  await page.click('[data-filter="reviewer"] > summary');
  await page.click('[data-filter="reviewer"] [data-filter-action="none"]');
  assert.equal(await page.$$eval('.comment:not([hidden])', nodes => nodes.length), 0);
  await page.focus('[data-filter-option="reviewer"][value="Technical Reviewer"]');
  await page.keyboard.press('Space');
  assert.equal(await page.$$eval('.comment:not([hidden])', nodes => nodes.every(node => node.dataset.reviewer === 'Technical Reviewer')), true);
  await page.click('[data-filter="reviewer"] [data-filter-action="all"]');
  await page.click('[data-filter="reviewer"] > summary');
  await page.setViewport({ width: 390, height: 844 });
  await page.evaluate(() => { location.hash = '#comment-2'; });
  await page.waitForSelector('#comment-2.is-active');
  await page.waitForFunction(() => {
    const top = document.querySelector('mark[data-comments~="comment-2"]').getBoundingClientRect().top;
    return top > document.getElementById('toolbar').offsetHeight && top < innerHeight / 2;
  });
  await page.waitForFunction(() => document.getElementById('status').textContent === '');
  await page.screenshot({ path: join(directory, 'mobile.png') });
  assert.equal(await page.$eval('#comment-2', el => getComputedStyle(el).position), 'fixed');
  assert.equal(await page.evaluate(() => {
    const nav = document.querySelector('.comment-navigation');
    const card = document.getElementById('comment-2');
    return nav.parentElement === card && Math.abs(nav.getBoundingClientRect().top - card.getBoundingClientRect().top) < 2 && nav.getBoundingClientRect().bottom <= card.querySelector('header').getBoundingClientRect().top;
  }), true);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.click('#comment-2 [data-action="next"]');
  await page.waitForSelector('#comment-3.is-active');
  assert.equal(await page.$eval('#comment-navigation', el => el.parentElement.id), 'comment-3');
  await page.click('#comment-3 [data-action="previous"]');
  await page.waitForSelector('#comment-2.is-active');
  await page.click('#comment-2 [data-action="close"]');
  assert.equal(await page.$('#comment-2.is-active'), null);
  await page.setViewport({ width: 320, height: 700 });
  for (const selector of ['.sections-menu', '[data-filter="priority"]', '[data-filter="reviewer"]', '#download-menu']) {
    await page.click(selector + ' > summary');
    assert.equal(await page.$eval(selector + ' .menu-panel', el => {
      const rect = el.getBoundingClientRect();
      return rect.left >= 0 && rect.right <= innerWidth;
    }), true);
    await page.click(selector + ' > summary');
  }
  await page.setViewport({ width: 1440, height: 1050 });
  await setPriorities(['major']);
  await page.emulateMediaType('print');
  assert.equal(await page.$eval('.paper', el => getComputedStyle(el).display), 'none');
  assert.equal(await page.$$eval('.comment', nodes => nodes.every(el => getComputedStyle(el).display !== 'none')), true);
  await page.evaluate(() => { document.body.classList.add('print-manuscript'); document.querySelector('.limitations').open = true; });
  assert.equal(await page.$eval('.paper', el => getComputedStyle(el).display), 'block');
  await page.pdf({ path: join(directory, 'print.pdf'), preferCSSPageSize: true, printBackground: true });
  await page.emulateMediaType('screen');
  const denseReview = { ...exampleReview, comments: Array.from({ length: 200 }, (_, i) => ({ ...exampleReview.comments[0], content: `Synthetic issue ${i + 1}. Explain recruitment and group assignment with enough detail to reproduce the study.` })) };
  const denseFile = join(directory, 'dense.html'); await writeFile(denseFile, renderReview(exampleDocument, denseReview).html);
  await page.goto(pathToFileURL(denseFile).href, { waitUntil: 'load' });
  await page.evaluate(() => { location.hash = '#comment-100'; });
  await page.waitForSelector('#comment-100.is-active');
  await page.waitForFunction(() => Math.abs(document.getElementById('comment-100').getBoundingClientRect().top - document.querySelector('mark').getBoundingClientRect().top) < 3);
  assert.equal(await page.evaluate(() => Math.abs(document.getElementById('comments-heading').getBoundingClientRect().top - document.getElementById('toolbar').getBoundingClientRect().bottom) < 2), true);
  assert.equal(await page.$$eval('.comment', nodes => {
    const sorted = nodes.map(el => el.getBoundingClientRect()).sort((a, b) => a.top - b.top);
    return sorted[0].top + scrollY >= 0 && sorted.every((rect, i) => !i || rect.top >= sorted[i - 1].bottom);
  }), true);
  await page.setJavaScriptEnabled(false);
  await page.goto(pathToFileURL(artifact).href);
  assert.equal(await page.$eval('.comment-content', el => getComputedStyle(el).display), 'block');
  assert.equal(await page.$eval('#download-menu', el => getComputedStyle(el).display), 'none');
  assert.deepEqual(network, []);
  assert.deepEqual(errors, []);
  console.log('Reader checks passed: offline, anchors, overlap, multi-select filters, embedded fonts, downloads, mobile, print, 200-comment layout, and no-JS fallback.');
  console.log('Artifacts: ' + directory);
} finally { await browser.close(); }
