import assert from 'node:assert/strict';
import http from 'node:http';
import { mkdir, mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { resolve, join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { build } from 'esbuild';
import puppeteer from 'puppeteer-core';
import { Client, StreamableHTTPClientTransport } from '@modelcontextprotocol/client';
import { createService } from '../src/server.js';
import { docxFixture } from '../test/fixtures.js';
await mkdir('data', {recursive:true}); const directory=await mkdtemp(resolve('data/mcp-app-test-'));
const service=await createService({baseUrl:'http://127.0.0.1:0',protectApp:false,adminToken:'',accessToken:''});
const origin=await service.listen(0);
const client=new Client({name:'app-test',version:'1'}, {capabilities:{extensions:{'io.modelcontextprotocol/ui':{mimeTypes:['text/html;profile=mcp-app']}}}});
const decode=result=>JSON.parse(result.content[0].text);
await client.connect(new StreamableHTTPClientTransport(new URL(origin+'/mcp')));
const bridge=await build({stdin:{contents:`import { AppBridge, PostMessageTransport } from '@modelcontextprotocol/ext-apps/app-bridge';
window.mount=async ({html,input,result,download=true,cancel=false})=>{
 if(window.bridge)await window.bridge.close();
 const frame=document.createElement('iframe');frame.style='width:100%;height:400px;border:0';frame.sandbox='allow-scripts allow-same-origin';document.body.replaceChildren(frame);
 const app=new AppBridge(null,{name:'test-host',version:'1'},{downloadFile:download?{}:undefined,message:{text:{}},openLinks:{}});
 app.onmessage=async p=>{window.message=p;return {};};
 app.onopenlink=async p=>{window.openedLink=p.url;return {};};
 if(download)app.ondownloadfile=async p=>{if(cancel){cancel=false;return {isError:true};}window.download=p.contents[0].resource;await window.saveFile(window.download.text);return {};};
 app.oninitialized=async()=>{await app.sendToolInput({arguments:input});await app.sendToolResult(result);};
 await app.connect(new PostMessageTransport(frame.contentWindow,frame.contentWindow));frame.srcdoc=html;window.bridge=app;
};`,resolveDir:process.cwd(),sourcefile:'app-host.js'},bundle:true,minify:true,write:false,format:'iife',platform:'browser'});
const host=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html');res.end('<!doctype html><script>'+bridge.outputFiles[0].text.replaceAll('</script','<\\/script')+'</script>');});
await new Promise(r=>host.listen(0,'127.0.0.1',r));
const browser=await puppeteer.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
try{
 const page=await browser.newPage();page.on('pageerror',e=>console.log('pageerror:',e.message));await page.setViewport({width:390,height:844});
 await page.exposeFunction('saveFile',text=>writeFile(join(directory,'review.html'),text));
 await page.goto('http://127.0.0.1:'+host.address().port);
 const info=await client.callTool({name:'get_review_instructions',arguments:{}});assert.match(info.content[0].text,/interactive.*card/i);
 const upload=await client.callTool({name:'prepare_document',arguments:{filename:'fixture.docx'}});
 const uploadResource=await client.readResource({uri:'ui://mim-review/upload.html'});
 assert.deepEqual(uploadResource.contents[0]._meta.ui.csp.connectDomains,[origin]);
 await page.evaluate(params=>window.mount(params),{html:uploadResource.contents[0].text,input:{filename:'fixture.docx'},result:upload});
 const frame=await page.waitForFrame(f=>f.parentFrame()!==null);
 await frame.waitForFunction(()=>!document.getElementById('upload-button').disabled).catch(async e=>{console.log(await frame.$eval('#status',el=>el.textContent));throw e;});
 const fixture=join(directory,'fixture.docx');await writeFile(fixture,docxFixture());
 await (await frame.$('#file')).uploadFile(fixture);await frame.click('#upload-button');
 await page.waitForFunction(()=>window.message?.content?.[0]?.text.includes('document_id'));
 const document_id=(await page.evaluate(()=>window.message.content[0].text)).match(/[a-f0-9]{48}/)[0];
 const review={document_id,summary:'## Summary\n\nSynthetic review fixture.',comments:[{text_snippet:'24 volunteers',content:'Explain the sample size rationale.',severity:'minor',reviewer:'Technical Reviewer'}],coverage:{technical:'limited',editorial:'skipped',references:'skipped'},limitations:['Synthetic fixture; no substantive review performed.']};
 const exported=await client.callTool({name:'export_review',arguments:review});
 assert.equal(decode(exported).delivery,'download_card');assert.ok(JSON.stringify(exported).length<2000);
 assert.equal(decode(exported).primary,undefined);
 const resource=await client.readResource({uri:'ui://mim-review/export.html'});
 await page.evaluate(params=>window.mount(params),{html:resource.contents[0].text,input:{...review,delivery:'download'},result:exported,cancel:true});
 const exportFrame=await page.waitForFrame(f=>f.parentFrame()!==null&&f!==frame);
 await exportFrame.waitForFunction(()=>!document.getElementById('download').disabled);
 await page.screenshot({path:join(directory,'download-card-mobile.png')});
 service.documents.clear(); // The HTML is already in the card's memory, independent of server expiry.
 await exportFrame.click('#download');await exportFrame.waitForFunction(()=>document.getElementById('status').textContent.includes('cancelled'));
 await exportFrame.click('#download');await page.waitForFunction(()=>!!window.download);
 const html=await readFile(join(directory,'review.html'),'utf8');assert.match(html,/id="anchor-1"/);assert.match(html,/Synthetic review fixture/);
 const reader=await browser.newPage();await reader.goto(pathToFileURL(join(directory,'review.html')).href);assert.match(await reader.$eval('body',el=>el.textContent),/sample size rationale/);
 await reader.screenshot({path:join(directory,'downloaded-review.png')});
 // Browser fallback uses the real scoped route and a saved local review JSON.
 const registered=decode(await client.callTool({name:'create_text_document',arguments:{filename:'fixture.md',text:'24 volunteers'}}));
 const fallbackReview={...review,document_id:registered.document_id};
 const fallbackExport=await client.callTool({name:'export_review',arguments:fallbackReview});
 const noDownloadPage=await browser.newPage();await noDownloadPage.goto('http://127.0.0.1:'+host.address().port);
 await noDownloadPage.evaluate(params=>window.mount(params),{html:resource.contents[0].text,input:{...fallbackReview,delivery:'download'},result:fallbackExport,download:false});
 const fallbackFrame=await noDownloadPage.waitForFrame(f=>f.parentFrame()!==null);
 await fallbackFrame.waitForFunction(()=>!document.getElementById('browser').hidden);
 await fallbackFrame.click('#browser');await noDownloadPage.waitForFunction(()=>!!window.openedLink);
 const browserLink=await noDownloadPage.evaluate(()=>window.openedLink);
 assert.equal(JSON.parse(Buffer.from(new URL(browserLink).hash.slice(8),'base64url').toString()).delivery,undefined);
 const context=await browser.createBrowserContext();const fallback=await context.newPage();
 const cdp=await fallback.createCDPSession();await cdp.send('Page.setDownloadBehavior',{behavior:'allow',downloadPath:directory});
 await fallback.goto(browserLink);
 await fallback.waitForFunction(()=>document.getElementById('export-status').textContent.includes('ready'));
 assert.equal(new URL(fallback.url()).hash,'');await fallback.click('#download-review');
 await fallback.waitForFunction(()=>document.getElementById('export-status').textContent.includes('Download started'));
 assert.equal(await fallback.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await context.close();console.log('MCP Apps upload, chat resume, host HTML download, cancel/retry, expiry independence, offline reader and browser fallback passed. '+directory);
}finally{await browser.close();await client.close();await service.close();await new Promise(r=>host.close(r));}
