import assert from 'node:assert/strict';
import http from 'node:http';
import { createHash, randomBytes } from 'node:crypto';
import { mkdir, mkdtemp, writeFile } from 'node:fs/promises';
import { resolve, join } from 'node:path';
import puppeteer from 'puppeteer-core';
import { Client, StreamableHTTPClientTransport } from '@modelcontextprotocol/client';
import { docxFixture } from '../test/fixtures.js';
import { createService } from '../src/server.js';

await mkdir('data', { recursive: true });
const directory = await mkdtemp(resolve('data/access-browser-'));
const adminToken = 'browser-test-admin-credential-at-least-32-characters';
const service = await createService({ baseUrl: 'http://127.0.0.1:0', protectApp: true, adminToken, accessDb: join(directory, 'access.sqlite') });
const origin = await service.listen(0);
const browser = await puppeteer.launch({ executablePath: process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true });
let client;
try {
  const context = browser.defaultBrowserContext();
  await context.overridePermissions(origin, ['clipboard-read', 'clipboard-write', 'clipboard-sanitized-write']);
  const admin = await browser.newPage(), page = await browser.newPage(), errors = [];
  for (const tab of [admin, page]) tab.on('pageerror', error => errors.push(error.message));
  await admin.bringToFront();
  await admin.setViewport({ width: 1360, height: 1000 });
  await admin.goto(origin + '/admin');
  await admin.type('#admin-token', adminToken); await admin.click('#admin-login button');
  await admin.waitForSelector('#dashboard', { visible: true });
  await admin.type('#person-name', 'Alex Example'); await admin.click('#create-invitation button');
  await admin.waitForSelector('#issued', { visible: true });
  const code = await admin.$eval('#issued-value', el => el.value);
  assert.match(code, /^[A-HJ-NP-Z2-9]{8}$/);
  const invitationUrl = await admin.$eval('#issued-url', el => el.value);
  assert.equal(invitationUrl, origin + '/?invite=' + code);
  await admin.click('#copy-issued-url');
  assert.equal(await admin.evaluate(() => navigator.clipboard.readText()), invitationUrl);
  assert.equal(await admin.$('#monitor'), null);
  assert.equal(await admin.$$('.admin-heading #refresh, .admin-heading #download-logs').then(items => items.length), 2);
  await admin.reload();
  await admin.type('#admin-token', adminToken); await admin.click('#admin-login button');
  await admin.waitForSelector('#dashboard', { visible: true });
  assert.doesNotMatch(await admin.$eval('#users', el => el.textContent), /Issue key/);
  await admin.click('#users button:nth-child(2)');
  await admin.waitForSelector('#issued', { visible: true });
  assert.equal(await admin.$eval('#issued-value', el => el.value), code);
  assert.equal(await admin.$eval('#issued-url', el => el.value), invitationUrl);
  assert.equal(await admin.$$('#keys tr').then(rows => rows.length), 0);
  await admin.screenshot({ path: join(directory, 'invitation-details.png') });
  await page.bringToFront();
  await page.setViewport({ width: 1440, height: 950 });
  await page.goto(origin);
  await page.waitForSelector('#invitation-form', { visible: true });
  assert.equal(await page.$eval('#connection-fields', el => el.hidden), true);
  await page.evaluate(() => document.fonts.ready);
  await page.screenshot({ path: join(directory, 'invitation-desktop.png') });
  await page.type('#invitation-code', 'wrong'); await page.click('#invitation-form button');
  await page.waitForSelector('#error', { visible: true });
  await page.$eval('#invitation-code', el => { el.value = ''; });
  await page.type('#invitation-code', code.toLowerCase()); await page.click('#invitation-form button');
  await page.waitForSelector('#connection-fields', { visible: true });
  assert.equal(await page.$eval('#invitation-code', el => el.value), '');
  assert.equal(await page.$('#sign-out'), null);
  assert.equal(await page.$('#private-note'), null);
  assert.doesNotMatch(await page.$eval('#connection-fields', el => el.textContent), /50 conversions|Basic usage|Expires|Single use/);
  await context.deleteCookie(...await context.cookies());
  await page.reload(); await page.waitForSelector('#invitation-form', { visible: true });
  await page.goto(origin + '/?invite=INVALID1');
  await page.waitForSelector('#error', { visible: true });
  assert.equal(new URL(page.url()).search, '');
  await page.waitForSelector('#invitation-form', { visible: true });
  await page.goto(invitationUrl + '&view=test#start');
  await page.waitForSelector('#connection-fields', { visible: true });
  assert.equal(new URL(page.url()).search, '?view=test');
  assert.equal(new URL(page.url()).hash, '#start');
  assert.equal(await page.$eval('#invitation-code', el => el.value), '');
  await page.click('#copy-prompt');
  await page.waitForFunction(() => document.getElementById('copy-prompt').dataset.copied === 'true');
  const prompt = await page.evaluate(() => navigator.clipboard.readText());
  assert.equal(prompt, await page.$eval('#setup-prompt', el => el.value));
  assert.match(prompt, /Connect to this MCP, confirm status using get_review_instructions/); assert.match(prompt, /await my manuscript for peer review/);
  const link = prompt.split('\n')[1];
  assert.ok(link.startsWith(origin + '/mcp/'));
  assert.equal(await page.$eval('#mcp-url', el => el.value), link);
  await page.click('#copy-url');
  await page.waitForFunction(() => document.getElementById('copy-url').dataset.copied === 'true');
  assert.equal(await page.evaluate(() => navigator.clipboard.readText()), link);
  const setupText = await fetch(link.replace('/mcp/', '/connect/')).then(r => r.text());
  const token = /Authorization header: Bearer (\S+)/.exec(setupText)[1];
  assert.equal(await fetch(link.replace('/mcp/', '/connect/')).then(r => r.text()), setupText);
  client = new Client({ name: 'browser-verification', version: '1' });
  await client.connect(new StreamableHTTPClientTransport(new URL(link)));
  assert.equal((await client.callTool({ name: 'list_guidance', arguments: {} })).isError, undefined);
  await page.evaluate(() => { navigator.clipboard.writeText = async () => { throw new DOMException('Blocked', 'NotAllowedError'); }; });
  await page.click('#copy-prompt');
  await page.waitForSelector('#error', { visible: true });
  assert.equal(await page.$eval('#setup-prompt', el => el.value), prompt);
  assert.equal(await page.$eval('#setup-prompt', el => el.selectionEnd - el.selectionStart), prompt.length);
  await page.reload(); await page.waitForSelector('#connection-fields', { visible: true });
  assert.equal(await page.evaluate(() => localStorage.length + sessionStorage.length), 0);
  assert.equal(await page.evaluate(() => document.cookie), '');
  assert.equal((await page.content()).includes(token), false);
  await page.waitForFunction(() => !document.getElementById('copy-prompt').disabled);
  assert.equal(await page.$eval('#setup-prompt', el => el.value), prompt);
  await page.screenshot({ path: join(directory, 'connected-desktop.png') });
  await page.setViewport({ width: 390, height: 844 });
  await page.screenshot({ path: join(directory, 'connected-mobile.png') });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  // An agent that cannot POST bytes can hand the user a private upload page.
  const upload = JSON.parse((await client.callTool({ name: 'prepare_document', arguments: { filename: 'browser-fixture.docx' } })).content[0].text);
  const manuscript = join(directory, 'browser-fixture.docx'); await writeFile(manuscript, docxFixture());
  const uploadPage = await browser.newPage();
  await uploadPage.setViewport({ width: 390, height: 844 });
  await uploadPage.goto(upload.browser_url);
  await uploadPage.screenshot({ path: join(directory, 'upload-mobile.png') });
  assert.equal(await uploadPage.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await (await uploadPage.$('#manuscript')).uploadFile(manuscript);
  await uploadPage.click('#upload-form button');
  await uploadPage.waitForFunction(() => document.getElementById('upload-status').textContent.startsWith('Uploaded.'));
  assert.equal((await client.callTool({ name: 'get_upload_status', arguments: { upload_id: upload.upload_id } })).isError, undefined);
  await uploadPage.close();
  const callback = http.createServer((req, res) => { res.end('Connected'); });
  await new Promise(resolve => callback.listen(0, '127.0.0.1', resolve));
  try {
    const redirect = `http://127.0.0.1:${callback.address().port}/callback`;
    const registration = await fetch(origin + '/oauth/register', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ client_name: 'Browser verification', redirect_uris: [redirect], token_endpoint_auth_method: 'none' }) }).then(r => r.json());
    const verifier = randomBytes(32).toString('base64url');
    const authorization = origin + '/oauth/authorize?' + new URLSearchParams({ client_id: registration.client_id, redirect_uri: redirect, response_type: 'code', resource: origin + '/mcp', state: 'browser-check', code_challenge_method: 'S256', code_challenge: createHash('sha256').update(verifier).digest('base64url') });
    await page.goto(authorization);
    assert.equal(await page.$('#code'), null, 'Remembered invitation should only need consent');
    await page.screenshot({ path: join(directory, 'oauth-returning.png') });
    await Promise.all([page.waitForNavigation(), page.click('button[value=allow]')]);
    assert.equal(new URL(page.url()).searchParams.get('state'), 'browser-check', await page.$eval('body', el => el.innerText));
    const exchange = await fetch(origin + '/oauth/token', { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ grant_type: 'authorization_code', code: new URL(page.url()).searchParams.get('code'), client_id: registration.client_id, redirect_uri: redirect, resource: origin + '/mcp', code_verifier: verifier }) });
    assert.equal(exchange.status, 200);
    const freshContext = await browser.createBrowserContext();
    try {
      const fresh = await freshContext.newPage(); await fresh.goto(authorization);
      await fresh.setViewport({ width: 390, height: 844 });
      await fresh.type('#code', code);
      await fresh.screenshot({ path: join(directory, 'oauth-invitation.png') });
      await Promise.all([fresh.waitForNavigation(), fresh.click('button[value=allow]')]);
      assert.equal(new URL(fresh.url()).searchParams.get('state'), 'browser-check');
    } finally { await freshContext.close(); }
  } finally { await new Promise(resolve => callback.close(resolve)); }
  const snapshot = await fetch(origin + '/api/admin/summary', { headers: { Authorization: 'Bearer ' + adminToken } }).then(r => r.json());
  const currentKey = snapshot.keys.find(key => !key.revoked);
  await fetch(origin + '/api/admin/revoke-key', { method: 'POST', headers: { Authorization: 'Bearer ' + adminToken, 'Content-Type': 'application/json' }, body: JSON.stringify({ id: currentKey.id }) });
  await page.goto(origin);
  await page.waitForSelector('#invitation-form', { visible: true });
  assert.equal(await page.$eval('#connection-fields', el => el.hidden), true);
  await page.type('#invitation-code', code); await page.click('#invitation-form button');
  await page.waitForFunction(() => !document.getElementById('copy-prompt').disabled && !document.getElementById('connection-fields').hidden);
  assert.notEqual(await page.$eval('#mcp-url', el => el.value), link);
  await admin.bringToFront(); await admin.click('#refresh');
  await admin.waitForFunction(() => document.getElementById('events').textContent.includes('list_guidance'));
  await admin.$eval('#issued', el => { el.hidden = true; });
  await admin.screenshot({ path: join(directory, 'admin-desktop.png') });
  await admin.setViewport({ width: 390, height: 844 });
  await admin.screenshot({ path: join(directory, 'admin-mobile.png') });
  assert.equal(await admin.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await admin.click('#users button');
  await admin.waitForFunction(() => document.getElementById('users').textContent.includes('Revoked'));
  await page.goto(invitationUrl); await page.waitForSelector('#invitation-form', { visible: true });
  await page.waitForSelector('#error', { visible: true });
  assert.equal(new URL(page.url()).search, '');
  await page.screenshot({ path: join(directory, 'invitation-mobile.png') });
  assert.equal((await fetch(origin + '/api/convert', { method: 'POST', headers: { Authorization: 'Bearer ' + token } })).status, 401);
  await admin.click('#logout');
  assert.equal(await admin.$eval('#issued-value', el => el.value), '');
  assert.equal(await admin.$eval('#issued-url', el => el.value), '');
  assert.equal(await admin.$eval('#admin-actions', el => el.hidden), true);
  await admin.reload(); await admin.waitForSelector('#admin-login', { visible: true });
  assert.equal(await admin.evaluate(() => localStorage.length + sessionStorage.length), 0);
  const openService = await createService({ baseUrl: 'http://127.0.0.1:0', protectApp: false, adminToken: '', accessToken: '' });
  try {
    const openOrigin = await openService.listen(0);
    await page.goto(openOrigin);
    await page.waitForFunction(() => !document.getElementById('copy-prompt').disabled);
    assert.equal(await page.$eval('#invitation-form', el => el.hidden), true);
    assert.equal(await page.$eval('#mcp-url', el => el.value), openOrigin + '/mcp');
    assert.ok((await page.$eval('#setup-prompt', el => el.value)).includes(openOrigin + '/mcp'));
  } finally { await openService.close(); }
  assert.deepEqual(errors, []);
  console.log('Invitation, admin, mobile, clipboard handoff, MCP authentication, and revocation checks passed. Screenshots: ' + directory);
} finally { await client?.close(); await browser.close(); await service.close(); }
